### PR TITLE
Update watch, Gulp v4

### PR DESCRIPTION
**Pull request by williamengbjerg**

### CODE REVIEW

**Comment by thangndird** [comment]
Hi @williamengbjerg 
I have change for you, But not working when gulp watch.

**Comment by williamengbjerg** [comment]
@thangndird Do you get any errors? I switched to another magento2-gulp [repo](https://github.com/bobmotor/magento-2-gulp). Can recommend you to try it out.

**Comment by thangndird** [comment]
@williamengbjerg . I have errors when change gulp watch:
gulp.watch([path + '**/*.less'],['less']); => gulp.watch([path + '**/*.less'],gulp.series('less'));
command process gulp watch --theme but when i change code glup watch not compile.
" I switched to another magento2-gulp repo". I will try it out

**Comment by williamengbjerg** [comment]
No activity from maintainer.

**Pull request closed without merging**
